import {
  issueSeverityLabels,
  issueStatusLabels,
  milestoneStatusLabels,
  projectPriorityLabels,
  projectStatusLabels,
  resourceTypeLabels,
  taskPriorityLabels,
  taskStatusLabels,
} from '../types/constants'
import type { AppData, Project, Task } from '../types/models'
import { formatDate } from '../utils/date'
import { isTauriRuntime } from './fileSystem'
import {
  calculateMilestoneProgress,
  calculateProgress,
  getProjectIssues,
  getProjectMilestones,
  getProjectNotes,
  getProjectResources,
  getProjectTasks,
  linkedEntityName,
} from '../utils/metrics'

export function generateProjectMarkdown(data: AppData, project: Project) {
  const tasks = getProjectTasks(data, project.id)
  const milestones = getProjectMilestones(data, project.id)
  const issues = getProjectIssues(data, project.id)
  const notes = getProjectNotes(data, project.id)
  const resources = getProjectResources(data, project.id)
  const progress = calculateProgress(tasks)
  const openTasks = tasks.filter((task) => task.status !== 'done')
  const completedTasks = tasks.filter((task) => task.status === 'done')
  const openIssues = issues.filter((issue) => issue.status !== 'resolved')

  return `# ${project.name}

Generated by PlanDesk on ${formatDate(new Date().toISOString())}

## Project

- Status: ${projectStatusLabels[project.status]}
- Priority: ${projectPriorityLabels[project.priority]}
- Category: ${project.category || 'Uncategorized'}
- Start date: ${formatDate(project.startDate)}
- Due date: ${formatDate(project.dueDate)}
- Root folder: ${project.rootFolderPath || 'Not linked'}
- Progress: ${progress}%

${project.description ? `## Description\n\n${project.description}\n` : ''}
${project.goal ? `## Goal\n\n${project.goal}\n` : ''}
## Progress Summary

- Total tasks: ${tasks.length}
- Completed tasks: ${completedTasks.length}
- Open tasks: ${openTasks.length}
- Open issues: ${openIssues.length}
- Linked resources: ${resources.length}
- Missing resources: ${resources.filter((resource) => resource.isMissing).length}

## Milestones

${milestones.length ? milestones.map((milestone) => `- ${milestone.title}: ${milestoneStatusLabels[milestone.status]}, due ${formatDate(milestone.dueDate)}, ${calculateMilestoneProgress(data, milestone.id)}% complete`).join('\n') : 'No milestones yet.'}

## Open Tasks

${openTasks.length ? openTasks.map((task) => `- ${task.title}: ${taskStatusLabels[task.status]}, ${taskPriorityLabels[task.priority]}, due ${formatDate(task.dueDate)}`).join('\n') : 'No open tasks.'}

## Completed Tasks

${completedTasks.length ? completedTasks.map((task) => `- ${task.title}`).join('\n') : 'No completed tasks yet.'}

## Issues

${issues.length ? issues.map((issue) => `- ${issue.title}: ${issueSeverityLabels[issue.severity]}, ${issueStatusLabels[issue.status]}${issue.resolutionNotes ? ` - ${issue.resolutionNotes}` : ''}`).join('\n') : 'No issues logged.'}

## Linked Resources

${resources.length ? resources.map((resource) => `- ${resource.label} (${resourceTypeLabels[resource.type]}, ${linkedEntityName(data, resource)}): ${resource.path}${resource.isMissing ? ' [Missing]' : ''}`).join('\n') : 'No linked resources.'}

## Notes

${notes.length ? notes.map((note) => `- ${note.title}`).join('\n') : 'No notes yet.'}

## Next Steps

${openTasks.slice(0, 5).map((task) => `- ${task.title}`).join('\n') || '- Add the next task in PlanDesk.'}
`
}

export function generateTaskCsv(tasks: Task[]) {
  const rows = [
    ['Title', 'Status', 'Priority', 'Due Date', 'Assignee', 'Tags'],
    ...tasks.map((task) => [
      task.title,
      taskStatusLabels[task.status],
      taskPriorityLabels[task.priority],
      task.dueDate,
      task.assignee ?? '',
      task.tags.join('; '),
    ]),
  ]

  return rows
    .map((row) =>
      row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(','),
    )
    .join('\n')
}

export type ExportFileResult = {
  ok: boolean
  message: string
}

const extensionFilters: Record<string, { name: string; extensions: string[] }> = {
  md: { name: 'Markdown', extensions: ['md'] },
  markdown: { name: 'Markdown', extensions: ['md', 'markdown'] },
  csv: { name: 'CSV', extensions: ['csv'] },
  json: { name: 'JSON', extensions: ['json'] },
  txt: { name: 'Text', extensions: ['txt'] },
}

function extensionForFilename(filename: string) {
  return filename.split('.').pop()?.toLowerCase() || 'txt'
}

function browserDownloadTextFile(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.style.display = 'none'
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export async function downloadTextFile(
  filename: string,
  content: string,
  type = 'text/plain',
): Promise<ExportFileResult> {
  try {
    if (isTauriRuntime()) {
      const [{ save }, { invoke }] = await Promise.all([
        import('@tauri-apps/plugin-dialog'),
        import('@tauri-apps/api/core'),
      ])
      const extension = extensionForFilename(filename)
      const filter = extensionFilters[extension] ?? extensionFilters.txt
      const path = await save({
        title: `Save ${filename}`,
        defaultPath: filename,
        filters: [filter],
      })

      if (!path) {
        return { ok: false, message: 'Export cancelled.' }
      }

      await invoke('save_text_file', { path, contents: content })
      return { ok: true, message: `Saved ${filename}.` }
    }

    browserDownloadTextFile(filename, content, type)
    return { ok: true, message: `Downloaded ${filename}.` }
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : `Could not save ${filename}.`,
    }
  }
}
